// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhoxrcsxhJRoGqKLK4EBkgSe373yuskTw',
    appId: '1:292217821555:web:1a37ec1e74470ef8a20d06',
    messagingSenderId: '292217821555',
    projectId: 'digimed-india-51fc8',
    authDomain: 'digimed-india-51fc8.firebaseapp.com',
    storageBucket: 'digimed-india-51fc8.firebasestorage.app',
    measurementId: 'G-4Z0Q08TBNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx_h5wi3wupcprAhJLI_fIg1ZgIMxgZi8',
    appId: '1:292217821555:android:0cb6392685e12343a20d06',
    messagingSenderId: '292217821555',
    projectId: 'digimed-india-51fc8',
    storageBucket: 'digimed-india-51fc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_9RRx6ZX0B0O-gSQppfO4-j6Fh4TSg3k',
    appId: '1:292217821555:ios:18c29890cb8a0be4a20d06',
    messagingSenderId: '292217821555',
    projectId: 'digimed-india-51fc8',
    storageBucket: 'digimed-india-51fc8.firebasestorage.app',
    iosBundleId: 'com.example.digimedindia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_9RRx6ZX0B0O-gSQppfO4-j6Fh4TSg3k',
    appId: '1:292217821555:ios:18c29890cb8a0be4a20d06',
    messagingSenderId: '292217821555',
    projectId: 'digimed-india-51fc8',
    storageBucket: 'digimed-india-51fc8.firebasestorage.app',
    iosBundleId: 'com.example.digimedindia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhoxrcsxhJRoGqKLK4EBkgSe373yuskTw',
    appId: '1:292217821555:web:de0044706337c27ea20d06',
    messagingSenderId: '292217821555',
    projectId: 'digimed-india-51fc8',
    authDomain: 'digimed-india-51fc8.firebaseapp.com',
    storageBucket: 'digimed-india-51fc8.firebasestorage.app',
    measurementId: 'G-0W9TBTEN44',
  );
}
